### ISSUE TITLE
Shortest Path node

### ISSUE THREAD

**Issue by tausendsasser** [3DSinghVFX/animation_nodes#146]
Hi, unfortunately it doesn't work. I followed all instructions exactly. ( https://www.youtube.com/watch?v=C-DTo-R_V6I&t=3s ) Unfortunately, paths are formed from each individual vertice. The paths are also built up in reverse and the curve objects then overlap.

Please Help. bye Marcel
[v01.zip](https://github.com/3DSinghVFX/animation_nodes/files/4567172/v01.zip)

Daily Release: 41fd1b49b89a4437b625c780651b6647.zip Blender: v2.82.7 Win10Pro

**Comment by 3DSinghVFX** [comment]
Hi :) Thanks for the feedback.
I have fixed the wrong direction of paths and added an option to change the direction of paths in https://github.com/3DSinghVFX/animation_nodes/commit/50559b853182c9261563189bbd0af63a4567f01b

Curves of paths will overlap because this way the [Dijkstra's algorithm](https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm) works. If you want to remove overlap then generate the paths as Line-Meshes then remove the doubles then convert into splines: 
![v01](https://user-images.githubusercontent.com/30294746/80857277-9e660a00-8c6e-11ea-9439-3549dfbf5b96.png)

![v02](https://user-images.githubusercontent.com/30294746/80857294-bf2e5f80-8c6e-11ea-8227-0d2bbd2536f8.png)

**Comment by tausendsasser** [comment]
Thank you for your time.
I installed the new build and exactly rebuilt your node setup. Unfortunately, the result is not correct. Now the paths are set up again from each vertices.
In addition, the double vertices are still present.
Thank you for your patience.
[v01a.zip](https://github.com/3DSinghVFX/animation_nodes/files/4567319/v01a.zip)

**Comment by 3DSinghVFX** [comment]
> Thank you for your time.
> I installed the new build and exactly rebuilt your node setup. Unfortunately, the result is not correct. Now the paths are set up again from each vertices.
> In addition, the double vertices are still present.
> Thank you for your patience.

You are welcome. 

You need to increase the `Distance` (in this case `0.001`) in the _BMesh Remove Doubles_ node.
[v01a.blend.zip](https://github.com/3DSinghVFX/animation_nodes/files/4567368/v01a.blend.zip)

**Comment by tausendsasser** [comment]
That worked. :) 
Unfortunately, the animation does not form from the defined Vertices 68 (Integer List). Do you also have a solution? :)

**Comment by 3DSinghVFX** [comment]
What do you mean by defined vertices 68? Please elaborate.

**Comment by tausendsasser** [comment]
The animation should start from a fixed position, the red square (Vertices No. 68). :) sorry my english is bad...

**Comment by 3DSinghVFX** [comment]
It is not starting from there because we have merged the vertices.

You can choose a particular path from the path-list:
![v01a](https://user-images.githubusercontent.com/30294746/80863325-10534900-8c99-11ea-9d10-6423667b5ec9.png)

[v01b.blend.zip](https://github.com/3DSinghVFX/animation_nodes/files/4567611/v01b.blend.zip)

**Comment by tausendsasser** [comment]
A big thank you. :)
The animation nodes are really really complicated.

**Comment by 3DSinghVFX** [comment]
Is it resolved? should I close this issue?
